/**
 * Diagnostics skill.md Generator
 * 
 * Generates skill-diagnostics.md combining all problem category and diagnostic rules
 * into a comprehensive Markdown document for guided problem diagnosis.
 */

import {
  InputValidationDefectsRule,
  AuthAuthorizationDefectsRule,
  DataProtectionDefectsRule,
  ConfigDeploymentDefectsRule,
  DependencySupplyChainDefectsRule,
  BusinessLogicDefectsRule
} from '../problems';

import type { DiagnosticGuide } from '../schemas/types';

const diagnosticRules: DiagnosticGuide[] = [
  InputValidationDefectsRule,
  AuthAuthorizationDefectsRule,
  DataProtectionDefectsRule,
  ConfigDeploymentDefectsRule,
  DependencySupplyChainDefectsRule,
  BusinessLogicDefectsRule,
];

function formatDiagnosticRule(rule: DiagnosticGuide): string {
  const steps = rule.diagnostic_steps.map((s) => `   - **Step ${s.order}: ${s.name}**: ${s.description}`).join('\n');
  const rootCauses = rule.common_root_causes.map((rc) => `   - [${rc.frequency}] **${rc.cause}**: ${rc.explanation}`).join('\n');
  const remediations = rule.remediations.map((r) => `   - [${r.priority}] ${r.action} (Difficulty: ${r.difficulty})`).join('\n');
  const triggers = rule.triggers.patterns.map((p) => `   - \`${p}\``).join('\n');
  const langs = rule.triggers.languages.join(', ');
  const cwe = rule.cwe_ids.join(', ');
  const owasp = rule.owasp_categories.join(', ');
  const verification = rule.verification_steps.map((v, i) => `   ${i + 1}. ${v}`).join('\n');

  const relatedAudit = rule.related_audit_rules.length > 0 ? rule.related_audit_rules.join(', ') : 'None';
  const relatedPentest = rule.related_pentest_rules.length > 0 ? rule.related_pentest_rules.join(', ') : 'None';

  return `### ${rule.id}: ${rule.name}

**Category**: ${rule.category} | **Severity**: ${rule.default_severity} | **CWE**: ${cwe} | **OWASP**: ${owasp}

**Trigger Patterns**:
${triggers}

**Supported Languages**: ${langs}

**Diagnostic Flow**:
${steps}

**Common Root Causes**:
${rootCauses}

**Remediation**:
${remediations}

**Verification Steps**:
${verification}

**Related Audit Rules**: ${relatedAudit}

**Related Pentest Rules**: ${relatedPentest}`;
}

/**
 * Generate diagnostics skill.md
 */
export function buildDiagnosticsSkill(): string {
  const diagnosticSection = diagnosticRules.map(formatDiagnosticRule).join('\n---\n\n');

  return `# HOS-Audit-Core: Problems & Diagnostics Rules

> Systematic problem categorization and guided diagnosis for security findings.

---

## Core Philosophy

- **Diagnosis over Assertion** - Don't just identify the problem, diagnose the root cause
- **Process over Conclusion** - Follow structured diagnostic steps, not one-line judgments
- **Evidence over Speculation** - Every diagnostic conclusion requires evidence
- **Fix over Flag** - Provide actionable remediation, not just problem identification

---

## Rule Inventory

| Category | Count | IDs |
|----------|-------|-----|
| Problem Diagnostics | ${diagnosticRules.length} | PD-001 ~ PD-006 |

## Diagnostic Workflow

1. **Problem Identification**: Use AR/PT rules to discover potential issues
2. **Categorization**: Map findings to PD rules for problem classification
3. **Deep Diagnosis**: Follow diagnostic steps to identify root cause
4. **Remediation**: Apply specific fix guidance with code examples
5. **Verification**: Confirm the fix using verification steps

---

## Problem Categories (PD)

${diagnosticSection}

---

## Usage

### How to Use Diagnostic Rules

1. When a finding is identified by an Audit Rule (AR) or Pentest Rule (PT), locate the matching Problem Diagnostic rule (PD)
2. Follow the diagnostic flow step by step to identify the specific defect
3. Check common root causes to understand why the defect exists
4. Apply the remediation guidance with provided code examples
5. Execute verification steps to confirm the fix is effective

### Example: Input Validation Finding

**Step 1**: AR-002 identifies missing input validation on user API endpoint
**Step 2**: Map to PD-001 (Input Validation Defects)
**Step 3**: Follow PD-001 diagnostic flow:
   - Identify all input sources (request body, query params, headers)
   - Check existing validation mechanisms (none found)
   - Assess bypass possibilities (all inputs unvalidated)
   - Verify context-appropriate validation (missing type checks)
**Step 4**: Apply remediation (whitelist validation with Zod/Bean Validation)
**Step 5**: Run verification steps (test all input paths with malicious payloads)

---

*Generated by HOS-Audit-Core | Problems & Diagnostics Module | ${new Date().toISOString().split('T')[0]}*
`;
}
