/**
 * MCP Tool: cad_robot_urdf
 * Generate URDF/SRDF files for robot models from CAD assemblies
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import type { URDFConfig, URDFJoint, URDFLink, URDFMaterial } from "../../types.js";
import { getConfig } from "../../utils/config.js";
import { logger } from "../../utils/logging.js";

const MODULE = "tool:cad_robot_urdf";

// ─── URDF XML Generator ──────────────────────────────────────
function generateURDFXml(config: URDFConfig): string {
  const lines: string[] = [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<robot name="${config.robotName}">`,
  ];

  // Materials
  if (config.materials && config.materials.length > 0) {
    lines.push("  <material>");
    for (const mat of config.materials) {
      lines.push(`    <name>${mat.name}</name>`);
      lines.push(`    <color rgba="${mat.color.join(" ")}"/>`);
    }
    lines.push("  </material>");
  }

  // Links
  for (const link of config.links) {
    lines.push(`  <link name="${link.name}">`);
    if (link.visual) {
      lines.push("    <visual>");
      lines.push(`      <geometry><mesh filename="${link.visual.geometry}"/></geometry>`);
      if (link.visual.material) {
        lines.push(`      <material name="${link.visual.material}"/>`);
      }
      lines.push("    </visual>");
    }
    if (link.collision) {
      lines.push("    <collision>");
      lines.push(`      <geometry><mesh filename="${link.collision.geometry}"/></geometry>`);
      lines.push("    </collision>");
    }
    if (link.inertial) {
      lines.push("    <inertial>");
      lines.push(`      <mass value="${link.inertial.mass}"/>`);
      if (link.inertial.origin) {
        lines.push(`      <origin xyz="${link.inertial.origin.join(" ")}"/>`);
      }
      lines.push("    </inertial>");
    }
    lines.push("  </link>");
  }

  // Joints
  for (const joint of config.joints) {
    lines.push(`  <joint name="${joint.name}" type="${joint.type}">`);
    lines.push(`    <parent link="${joint.parent}"/>`);
    lines.push(`    <child link="${joint.child}"/>`);
    if (joint.origin) {
      lines.push(`    <origin xyz="${joint.origin.xyz.join(" ")}" rpy="${joint.origin.rpy.join(" ")}"/>`);
    }
    if (joint.axis) {
      lines.push(`    <axis xyz="${joint.axis.join(" ")}"/>`);
    }
    if (joint.limit) {
      lines.push(
        `    <limit lower="${joint.limit.lower}" upper="${joint.limit.upper}" effort="${joint.limit.effort}" velocity="${joint.limit.velocity}"/>`,
      );
    }
    lines.push("  </joint>");
  }

  lines.push("</robot>");
  return lines.join("\n");
}

// ─── SRDF XML Generator ──────────────────────────────────────
function generateSRDFXml(config: URDFConfig): string {
  const lines: string[] = [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<robot name="${config.robotName}">`,
    "  <!-- SRDF generated by HOS-CAD-Builder -->",
  ];

  // Group state
  lines.push('  <group name="all">');
  for (const joint of config.joints) {
    if (joint.type !== "fixed") {
      lines.push(`    <joint name="${joint.name}"/>`);
    }
  }
  lines.push("  </group>");

  // End effectors (last link)
  if (config.links.length > 0) {
    const lastLink = config.links[config.links.length - 1];
    lines.push(`  <end_effector name="end_effector" group="all" parent_link="${lastLink.name}"/>`);
  }

  // Disable collisions between adjacent links
  for (const joint of config.joints) {
    lines.push(`  <disable_collisions link1="${joint.parent}" link2="${joint.child}"/>`);
  }

  lines.push("</robot>");
  return lines.join("\n");
}

// ─── Template Robots ─────────────────────────────────────────
const TEMPLATES: Record<string, () => URDFConfig> = {
  "simple-arm": (): URDFConfig => ({
    robotName: "simple_arm",
    materials: [
      { name: "grey", color: [0.5, 0.5, 0.5, 1.0] },
      { name: "blue", color: [0.0, 0.0, 0.8, 1.0] },
    ],
    links: [
      { name: "base_link", visual: { geometry: "base_link.stl", material: "grey" } },
      { name: "shoulder_link", visual: { geometry: "shoulder.stl", material: "grey" } },
      { name: "upper_arm_link", visual: { geometry: "upper_arm.stl", material: "blue" } },
      { name: "forearm_link", visual: { geometry: "forearm.stl", material: "blue" } },
      { name: "wrist_link", visual: { geometry: "wrist.stl", material: "grey" } },
      { name: "end_effector_link", visual: { geometry: "gripper.stl", material: "grey" } },
    ],
    joints: [
      { name: "shoulder_pan", type: "revolute", parent: "base_link", child: "shoulder_link",
        origin: { xyz: [0, 0, 0.1], rpy: [0, 0, 0] }, axis: [0, 0, 1],
        limit: { lower: -3.14, upper: 3.14, effort: 50, velocity: 1.0 } },
      { name: "shoulder_lift", type: "revolute", parent: "shoulder_link", child: "upper_arm_link",
        origin: { xyz: [0, 0, 0.05], rpy: [0, 0, 0] }, axis: [0, 1, 0],
        limit: { lower: -1.57, upper: 1.57, effort: 50, velocity: 1.0 } },
      { name: "elbow", type: "revolute", parent: "upper_arm_link", child: "forearm_link",
        origin: { xyz: [0, 0, 0.3], rpy: [0, 0, 0] }, axis: [0, 1, 0],
        limit: { lower: -2.0, upper: 2.0, effort: 30, velocity: 1.5 } },
      { name: "wrist", type: "revolute", parent: "forearm_link", child: "wrist_link",
        origin: { xyz: [0, 0, 0.25], rpy: [0, 0, 0] }, axis: [0, 0, 1],
        limit: { lower: -3.14, upper: 3.14, effort: 10, velocity: 2.0 } },
      { name: "gripper_joint", type: "fixed", parent: "wrist_link", child: "end_effector_link",
        origin: { xyz: [0, 0, 0.05], rpy: [0, 0, 0] } },
    ],
  }),

  "differential-drive": (): URDFConfig => ({
    robotName: "diff_drive_robot",
    materials: [
      { name: "black", color: [0.1, 0.1, 0.1, 1.0] },
      { name: "red", color: [0.8, 0.0, 0.0, 1.0] },
    ],
    links: [
      { name: "base_link", visual: { geometry: "base.stl", material: "black" } },
      { name: "left_wheel", visual: { geometry: "wheel.stl", material: "black" } },
      { name: "right_wheel", visual: { geometry: "wheel.stl", material: "black" } },
      { name: "sensor_link", visual: { geometry: "sensor.stl", material: "red" } },
    ],
    joints: [
      { name: "left_wheel_joint", type: "continuous", parent: "base_link", child: "left_wheel",
        origin: { xyz: [0, 0.1, 0], rpy: [1.5708, 0, 0] }, axis: [0, 0, 1] },
      { name: "right_wheel_joint", type: "continuous", parent: "base_link", child: "right_wheel",
        origin: { xyz: [0, -0.1, 0], rpy: [1.5708, 0, 0] }, axis: [0, 0, 1] },
      { name: "sensor_joint", type: "fixed", parent: "base_link", child: "sensor_link",
        origin: { xyz: [0.1, 0, 0.1], rpy: [0, 0, 0] } },
    ],
  }),
};

export const robotTool = {
  name: "cad_robot_urdf",
  description:
    "Generate URDF and SRDF robot description files from a robot configuration. " +
    "Supports custom configurations and predefined templates (simple-arm, differential-drive).",
  inputSchema: {
    type: "object" as const,
    properties: {
      robot_name: {
        type: "string",
        description: "Name of the robot",
      },
      template: {
        type: "string",
        enum: ["simple-arm", "differential-drive"],
        description: "Use a predefined robot template (ignores other params if set)",
      },
      joints: {
        type: "array",
        description: "Array of joint definitions",
        items: {
          type: "object",
          properties: {
            name: { type: "string" },
            type: { type: "string", enum: ["revolute", "continuous", "prismatic", "fixed", "planar", "floating"] },
            parent: { type: "string" },
            child: { type: "string" },
          },
        },
      },
      links: {
        type: "array",
        description: "Array of link definitions",
        items: {
          type: "object",
          properties: {
            name: { type: "string" },
          },
        },
      },
    },
    required: [],
  },

  async handler(args: { robot_name?: string; template?: string; joints?: any[]; links?: any[] }) {
    logger.info(MODULE, `Generating URDF for "${args.template ?? args.robot_name ?? "custom"}"`);

    try {
      let config: URDFConfig;

      if (args.template && TEMPLATES[args.template]) {
        config = TEMPLATES[args.template]();
      } else {
        config = {
          robotName: args.robot_name ?? "my_robot",
          joints: (args.joints ?? []) as URDFJoint[],
          links: (args.links ?? []) as URDFLink[],
        };
      }

      const urdfXml = generateURDFXml(config);
      const srdfXml = generateSRDFXml(config);

      // Write files
      const outputDir = getConfig().outputDir;
      const urdfPath = join(outputDir, `${config.robotName}.urdf`);
      const srdfPath = join(outputDir, `${config.robotName}.srdf`);
      writeFileSync(urdfPath, urdfXml, "utf-8");
      writeFileSync(srdfPath, srdfXml, "utf-8");

      logger.info(MODULE, `Generated URDF: ${urdfPath}`);
      logger.info(MODULE, `Generated SRDF: ${srdfPath}`);

      const lines: string[] = [
        "## Robot URDF Generated\n",
        `**Robot**: ${config.robotName}`,
        `**Links**: ${config.links.length}`,
        `**Joints**: ${config.joints.length}`,
        `\n**URDF**: ${urdfPath}`,
        `**SRDF**: ${srdfPath}`,
        "\n### URDF Preview\n```xml",
        urdfXml.substring(0, 2000),
        urdfXml.length > 2000 ? "\n... (truncated)" : "",
        "\n```",
      ];

      return {
        content: [{ type: "text" as const, text: lines.join("\n") }],
        isError: false,
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      logger.error(MODULE, `URDF generation failed: ${msg}`);
      return {
        content: [{ type: "text" as const, text: `**Error**: ${msg}` }],
        isError: true,
      };
    }
  },
};
